apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
      - name: insurance-container
        image: sdfa777/insurance-star_agile-project-3:3.0 # Use your actual image
        ports:
        - containerPort: 8081
